function interfata(A1,A2,R1,R2,f1,f2,tip,v1,v2,tip1)
%Nume proiect
figure('Name','Proiect GAC',...
            'Units','normalized',...
            'Position',[0 0 1 0.89],...
            'NumberTitle','off','color','#BFBFBF');
%Titlul
uicontrol('Style','Text',...
    'units','normalized',...
    'position',[0.3 0.95 0.35 0.04],...
    'BackgroundColor','#BFBFBF',...
    'FontSize',16,...
    'String','A de instrumentatie cu AO');
subplot(3, 3, 1);
w=imread('circuit.jpg');
image(w);
axis off;

%Tabelul cu datele de intrare

uibuttongroup('Visible','on',...
              'BackgroundColor','#BFBFBF',...
              'ForegroundColor','black',...
              'FontSize',12,...
              'TitlePosition','centertop',...
              'Title','Date de intrare',...
              'Position',[0.04 0.3 0.20 0.35]);
          
%Amplitudinea semnalului 1
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.06,0.575,0.12,0.03],...
    'BackgroundColor','#BFBFBF',...
    'String','Amplitudinea1 A1[V]:');

%Amplitudinea semnalului 2
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.06,0.525,0.12,0.03],...
    'BackgroundColor','#BFBFBF',...
    'String','Amplitudinea2 A2[V]:');

%Frecventa semnal 1
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.06,0.475,0.12,0.03],...
    'BackgroundColor','#BFBFBF',...
    'String','Frecventa1 F1[Hz]:');

%Frecventa semnal 2
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.06,0.425,0.12,0.03],...
    'BackgroundColor','#BFBFBF',...
    'String','Frecventa 2 F2[Hz]:');

%Rezistenta 1
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.06,0.375,0.12,0.03],...
    'BackgroundColor','#BFBFBF',...
    'String','Rezistenta 1 R1[Ohm]:');

%Rezistenta 2
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.06,0.325,0.12,0.03],...
    'BackgroundColor','#BFBFBF',...
    'String','Rezistenta 2 R2[Ohm]:');


%citirea datelor de intrare
%Amplitudine 1
amplitudine1=uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.175 0.575 0.05 0.03],...
          'String',A1,...
          'Callback','A1=abs(str2num(get(gco,''String'')));close;interfata(A1,A2,R1,R2,f1,f2,tip,v1,v2,tip1)');
%Amplitudine 2
amplitudine2=uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.175 0.525 0.05 0.03],...
          'String',A2,...
          'Callback','A2=abs(str2num(get(gco,''String'')));close;interfata(A1,A2,R1,R2,f1,f2,tip,v1,v2,tip1)');
%Frecventa primului semnal      
frecventa1=uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.175 0.475 0.05 0.03],...
          'String',f1,...
          'Callback','f1=abs(str2num(get(gco,''String'')));close;interfata(A1,A2,R1,R2,f1,f2,tip,v1,v2,tip1)');
%Frecventa celui de-al doilea semnal
frecventa2=uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.175 0.425 0.05 0.03],...
          'String',f2,...
          'Callback','f2=abs(str2num(get(gco,''String'')));close;interfata(A1,A2,R1,R2,f1,f2,tip,v1,v2,tip1)');
%Rezsitenta 1
uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.175 0.375 0.05 0.03],...
          'String',R1,...
          'Callback','R1=abs(str2num(get(gco,''String'')));close;interfata(A1,A2,R1,R2,f1,f2,tip,v1,v2,tip1)');
%Rezistennta 2      
uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.175 0.325 0.05 0.03],...
          'String',R2,...
          'Callback','R2=abs(str2num(get(gco,''String'')));close;interfata(A1,A2,R1,R2,f1,f2,tip,v1,v2,tip1)');

      
%Tabelul cu datele de iesire  
uibuttongroup('Visible','on',...
              'BackgroundColor','#BFBFBF',...
              'ForegroundColor','black',...
              'FontSize',12,...
              'TitlePosition','centertop',...
              'Title','Date de iesire',...
              'Position',[0.24 0.35 0.20 0.3]);
          
%Tensiunea in punctul 3 (v01)
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.26,0.575,0.12,0.03],...
    'BackgroundColor','#BFBFBF',...
    'String','Vo1 [V]:');

%Tensiunea in punctul 4 (v02)
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.26,0.525,0.12,0.03],...
    'BackgroundColor','#BFBFBF',...
    'String','Vo2 [V]:');

%Tensiunea de iesire (v0)
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.26,0.475,0.12,0.03],...
    'BackgroundColor','#BFBFBF',...
    'String','Vo [V]:');
%Amplificare in tensiune
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.26,0.425,0.12,0.03],...
    'BackgroundColor','#BFBFBF',...
    'String','Amplificarea:');
%Curentul prin rezistenta de amplificare
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.26,0.375,0.12,0.03],...
    'BackgroundColor','#BFBFBF',...
    'String','Curentul prin R Amplificare [A]:');




%Tipul semnalului
grup=uibuttongroup('Visible','on',...
              'BackgroundColor','#BFBFBF',...
              'ForegroundColor','black',...
              'FontSize',12,...
              'TitlePosition','centertop',...
              'Title','Tipul semnalului',...
              'Position',[0.378 0.725 0.13 0.20]);
 %continuu         
r1=uicontrol('Style','Radiobutton',...
    'Units','Normalized',...
    'Position',[0.10,0.80,0.80,0.17],...
    'BackgroundColor','#BFBFBF',...
    'FontSize',8,...
   'value',tip,...
    'String','Semnal continuu',...
    'Callback','tip=get(gco,''value'');close;interfata(A1,A2,R1,R2,f1,f2,0,v1,v2,tip1)',...
    'Parent',grup); 

%alternativ
r2=uicontrol('Style','Radiobutton',...
    'Units','Normalized',...
    'Position',[0.10,0.60,0.80,0.17],...
    'BackgroundColor','#BFBFBF',...
    'FontSize',8,...
    'value',tip,...
    'String','Semnal alternativ',...
    'Callback','tip=get(gco,''value'');close;interfata(A1,A2,R1,R2,f1,f2,1,v1,v2,tip1)',...
    'Parent',grup); 
%in cazul in care alegem semnalul continuu acestea sunt valorile tensiunii
%v1
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.1,0.2,0.30,0.17],...
    'BackgroundColor','#BFBFBF',...
    'FontSize',10,...
    'FontWeight','bold',...
    'Parent',grup,...
    'String','V1 [V]:');
%v2
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.1,0.05,0.30,0.17],...
    'BackgroundColor','#BFBFBF',...
    'FontSize',10,...
    'FontWeight','bold',...
    'Parent',grup,...
    'String','V2 [V]:');
%butoanele edit pentru cele doua tensiuni - needitabile daca alegem semnalul alternativ
tensiune1=uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.5 0.2 0.40 0.17],...
          'String',v1,...
          'FontSize',10,...
          'Parent',grup,...
          'Callback','v1=str2num(get(gco,''String''));close;interfata(A1,A2,R1,R2,f1,f2,0,v1,v2,tip1)');
tensiune2=uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.5 0.05 0.40 0.17],...
          'String',v2,...
          'FontSize',10,...
          'Parent',grup,...
          'Callback','v2=str2num(get(gco,''String''));close;interfata(A1,A2,R1,R2,f1,f2,0,v1,v2,tip1)');

%calcule pentru vo1, vo2, vo, amplificarea si curentul prin r amplificare

vo1=v1+(R1/R2)*(v1-v2);
vo2= v2-(R1/R2)*(v1-v2);
vo=vo1-vo2;
i=(v1-v2)/R2;
amp=1+(2*R1/R2);
%afisam valorile obtinute in urma calculelor
%afisare vo1
primat=uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.375,0.555,0.05,0.05],...
          'BackgroundColor','#BFBFBF',...
          'String',vo1);
%afisare vo2      
doit=uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.375,0.505,0.05,0.05],...
          'BackgroundColor','#BFBFBF',...
          'String',vo2);
%afisare vo     
tf=uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.375,0.455,0.05,0.05],...
          'BackgroundColor','#BFBFBF',...
          'String',vo);
%afisare amplitudine - atat in cazul cc cat si ca
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.375,0.405,0.05,0.05],...
          'BackgroundColor','#BFBFBF',...
          'String',amp);
%afisare curent
curent=uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.375,0.355,0.05,0.05],...
          'BackgroundColor','#BFBFBF',...
          'String',i);

if(tip==1)%daca am ales semnal alternativ
   
          set(primat,'Visible','off'); %ascundem vo1
          set(doit,'Visible','off');   %ascundeam vo2
          set(tf,'Visible','off');     %ascundem vo
          set(curent,'Visible','off');  %ascundem curentul
          set(r1,'Visible','on');       
          set(r2,'Visible','on');
          set(tensiune1,'enable','off');%nu permitem editarea v1
          set(tensiune2,'enable','off');%nu permitem editarea v2
          
 %checkboxurile cu ajutorul carora putem alege pe care semnal sa il afisam-v1 sau v2        
checkbox1= uicontrol('Style','Checkbox',...
'Units','normalized',...
'String','V1',...
'BackgroundColor',[0.90 0.85  0.9],...
'Position', [0.93 .85 .05 .05],...
'Callback','tip1=1;close;interfata(A1,A2,R1,R2,f1,f2,tip,v1,v2,tip1)');

checkbox2= uicontrol('Style','Checkbox',...
'Units','normalized',...
'String','V2',...
'BackgroundColor',[0.90 0.85  0.9],...
'Position', [0.93 .78 .05 .05],...
'Callback','tip1=2;close;interfata(A1,A2,R1,R2,f1,f2,tip,v1,v2,tip1)');

if(tip1==1) %daca alegem sa vizualizam semnalul 1...grafice
subplot('position',[0.55 0.7 0.35 0.2])
T1=1/f1;                
t1=(0:T1/100:3*T1);   %am ales implicit afisarea pe 3 perioade        
semnal1=A1*sin(2*pi*f1*t1);
plot(t1,semnal1,'b','linewidth',2); 
title('Primul semnal de intrare','FontWeight','bold'); 
ylabel('V1 [V]','Fontangle','normal');
xlabel('Timpul [s]','Fontangle','normal');
grid on;
hold on;
end

if(tip1==2) %daca alegem semnalul 2...grafice
subplot('position',[0.55 0.7 0.35 0.2])
T2=1/f2;                
t2=(0:T2/100:3*T2);    %am ales implicit afisarea pe 3 perioade       
semnal2=A2*sin(2*pi*f2*t2);
plot(t2,semnal2,'b','linewidth',2); 
title('Al doilea semnal de intrare','FontWeight','bold'); 
ylabel('V2 [V]','Fontangle','normal');
xlabel('Timpul [s]','Fontangle','normal');
grid on;
hold on;
end

if tip1==1 %valori pentru cazul in care vrem sa afisam unuele din grafice

    set(checkbox1,'value',1)
    set(checkbox2,'value',0)
   
elseif tip1==2
   set(checkbox1,'value',0)
    set(checkbox2,'value',1)
    
end
%afisarea semnalului de iesire
T1=1/f1;                
t1=(0:T1/100:3*T1);    %am ales implicit afisarea pe 3 perioade      
semnal1=A1*sin(2*pi*f1*t1);
T2=1/f2;                
t2=(0:T2/100:3*T2);          
semnal2=A2*sin(2*pi*f2*t2);
semnaliesire=semnal1-semnal2;
subplot('position',[0.55 0.4 0.35 0.2])
plot(t1,amp*semnaliesire,'b','linewidth',2); 
title('Semnalul de iesire','FontWeight','bold'); 
ylabel('Vout [V]','Fontangle','normal');
xlabel('Timpul [s]','Fontangle','normal');
grid on;
hold on;
   
elseif (tip==0)
%daca am ales semnal continuu
   
            set(amplitudine1,'enable','off'); %nu putem modifica amplitudinea 1 si 2
            set(amplitudine2,'enable','off'); 
            set(frecventa1,'enable','off'); %nu putem modifica frecventele 1 si 2
            set(frecventa2,'enable','off');  
      
end

%buton inchidere
uicontrol('Style','pushbutton',... 
'Units','normalized',...
'Position',[0.9 0.95 0.08 .05],...
'string','Close',...
'Callback','close');
%bara principala
f=uimenu('Label','Proiect');
uimenu(f,'Label','Documentatie','Callback','open(''word.pdf'')');%documentatia
uimenu(f,'Label','Prezentare ','Callback','open (''ppt.pdf'')');        %prezentarea
uimenu(f,'Label','Bibliografie','Callback','open(''Bibliografie.pdf'')');%bibliografia
uimenu(f,'Label','Iesire','Callback','close',...
        'Separator','on','Accelerator','Q');%buton iesire


